// Generated by CoffeeScript 1.7.1
var Tile;

Tile = IgeEntity.extend({
  classId: 'Tile',
  init: function(_size) {
    this._size = _size;
    IgeEntity.prototype.init.call(this);
    this._lights = {};
    this._lights.l = new Light(Light.TYPE.SIDE).translateTo(-this._size / 2, 0, 0).depth(0).mount(this);
    this._lights.t = new Light(Light.TYPE.SIDE).rotateTo(0, 0, 1.57).translateTo(0, -this._size / 2, 0).depth(0).mount(this);
    this._lights.f = new Light(Light.TYPE.DIAG).depth(1).mount(this);
    this._lights.b = new Light(Light.TYPE.DIAG).rotateTo(0, 0, 1.57).depth(1).mount(this);
    this._lights.v = new Light(Light.TYPE.MID).depth(2).mount(this);
    return this._lights.h = new Light(Light.TYPE.MID).rotateTo(0, 0, 1.57).depth(2).mount(this);
  }
});

if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
  module.exports = Tile;
}
