// Generated by CoffeeScript 1.7.1
var Tile;

Tile = IgeEntity.extend({
  classId: 'Tile',
  init: function(_size) {
    this._size = _size;
    IgeEntity.prototype.init.call(this);
    this._l = new IgeEntity().texture(SL.tex['side']).dimensionsFromCell().translateTo(-this._size / 2, 0, 0).mount(this);
    return this._t = new IgeEntity().texture(SL.tex['side']).dimensionsFromCell().rotateTo(0, 0, 1.57).translateTo(0, -this._size / 2, 0).mount(this);
  }
});

if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
  module.exports = Tile;
}
